### ISSUE TITLE
About loss computation

### ISSUE THREAD

**Issue by white2018** [brooklyn1900/CRAFT_pytorch#5]
@brooklyn1900 Great job!!!

I run your training code. However, it works only the following codes are appended in loss function cal_synthText_loss.

    score_text = score_text.cpu()
    score_link = score_link.cpu()
    labels_region = labels_region.cpu()
    labels_affinity = labels_affinity.cpu()

Does it mean gpu is not involved in the loss computation? If so, how to make it happen that gpu is used in training phase? Thanks a lot

Looking forward to your advice.

**Comment by chantcalf** [comment]
When using GPU, you can try change the responding codes in loss : "np.where(XXX.cpu())".

**Comment by white2018** [comment]
> When using GPU, you can try change the responding codes in loss : "np.where(XXX.cpu())".

I am wondering whether .cpu() is able to make use of GPU or not

**Comment by chantcalf** [comment]
I  only  change the "np.where" operation to CPU, whereas keep the other operations in GPU.
I try in the following way instead of "labels_region = labels_region.cpu()":
    labels_region_bak = labels_region.cpu()
    ...... np.where(labels_region_bak > 0.1) .......

**Comment by white2018** [comment]
> I only change the "np.where" operation to CPU, whereas keep the other operations in GPU.
> I try in the following way instead of "labels_region = labels_region.cpu()":
> labels_region_bak = labels_region.cpu()
> ...... np.where(labels_region_bak > 0.1) .......

Great job!!! Thanks a lot

**Comment by zcswdt** [comment]
> > I only change the "np.where" operation to CPU, whereas keep the other operations in GPU.
> > I try in the following way instead of "labels_region = labels_region.cpu()":
> > labels_region_bak = labels_region.cpu()
> > ...... np.where(labels_region_bak > 0.1) .......
> 
> Great job!!! Thanks a lot

我在训练的时候遇到这个问题了，请教你一下，如何修改呢？谢谢！
`len train data: 1145
epoch =  0
Traceback (most recent call last):
  File "train_finetune.py", line 143, in <module>
    model_save_prefix =  model_save_prefix)
  File "train_finetune.py", line 96, in train
    device)
  File "/data/craft/CRAFT_pytorch-master/utils/cal_loss.py", line 78, in cal_fakeData_loss
    loss1_fg = loss1_fg * sc_map[np.where(labels_region.cpu() > 0.1)]
RuntimeError: expected device cpu and dtype Float but got device cuda:0 and dtype Float
`
